name: "Rust: Build, Test, Publish Coverage"

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6
        with:
          cache-all-crates: "true"
      - uses: taiki-e/install-action@7cb2cdb5024b2b45585f150af1ee02e24b87edd7
        with:
          tool: cargo-binstall
      - name: Build, Test, Publish Coverage
        run: |
          if [ -n "${{ secrets.COVERALLS_REPO_TOKEN }}" ]; then
            cargo binstall --no-confirm cargo-tarpaulin --force --only-signed
            cargo tarpaulin --all-features --avoid-cfg-tarpaulin --tests --verbose --skip-clean --coveralls ${{ secrets.COVERALLS_REPO_TOKEN }} --timeout 120
          else
            echo "Code Coverage step is skipped on PRs from forks."
            cargo binstall --no-confirm --force --only-signed
            cargo nextest run --verbose --all-features
          fi
