name: "Rust: Build, Test, Publish Coverage"

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

# Auto-abort duplicate jobs (e.g. job being triggered again on push to open PR)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: "llvm-tools-preview"
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6
        with:
          cache-all-crates: "true"
      - uses: taiki-e/install-action@7cb2cdb5024b2b45585f150af1ee02e24b87edd7
        with:
          tool: cargo-binstall
      - name: Install dependencies
        run: |
          cargo binstall --no-confirm --force --only-signed cargo-llvm-cov cargo-nextest
      - name: Build, Test, Publish Coverage
        run: |
          if [ -n "${{ secrets.COVERALLS_REPO_TOKEN }}" ]; then
            mkdir -p coverage
            cargo +nightly llvm-cov nextest --lcov --output-path coverage/lcov.info --branch --mcdc --all-targets --all-features --workspace
          else
            echo "Code Coverage step is skipped on PRs from forks."
            cargo nextest run --verbose --all-features
          fi
      - name: Publish coverage to Coveralls.io
        if: github.repository == 'polyphony-chat/sonata'
        uses: coverallsapp/github-action@v2
        with:
          file: "coverage/lcov.info"
          format: "lcov"
